language: node_js
node_js:
  - "4"
  - "6"
  - "7"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
    - build-essential
    - libudev-dev
    - g++-4.8
before_script:
  - mkdir ~/.android
  - touch ~/.android/adbkey.pub
  - touch ~/.android/adbkey
  - echo "public" > ~/.android/adbkey.pub
  - echo "private" > ~/.android/adbkey
after_success:
  - gulp coveralls
