language: node_js
node_js:
  - "0.12"
addons:
  apt:
    packages:
    - build-essential
    - libudev-dev
before_script:
  - mkdir ~/.android
  - touch ~/.android/adbkey.pub
  - touch ~/.android/adbkey
  - echo "public" > ~/.android/adbkey.pub
  - echo "private" > ~/.android/adbkey
after_success:
  - gulp coveralls